### ISSUE TITLE
Feature request: A tiny release with Ruby 3 support

### ISSUE THREAD

**Issue by olleolleolle** [drbrain/net-http-persistent#123]
TL;DR: It'd be so nice to have the latest commit as a released gem.

## Details

I attempted to run `ruby-head` to try out Ruby 3.

I pointed at this repo.

There wasn't a `.gemspec` file, so Bundler wasn't equipped to use the Git repo as a "development version" of the gem.

Example of being out of luck:

```
$ bundle
Fetching https://github.com/drbrain/net-http-persistent.git
Fetching gem metadata from https://rubygems.org/.........
Could not find gem 'net-http-persistent (>= 3.0)' in https://github.com/drbrain/net-http-persistent.git (at master@2379e37).
The source does not contain any versions of 'net-http-persistent'
```

Thanks for maintaining this great gem!

**Comment by connorshea** [comment]
🙏 I would greatly appreciate this with 3.0 coming on Friday

**Comment by gkellogg** [comment]
I have about 15 gems with direct or indirect dependencies that can’t load on ruby-head because of this. Please release at least a minimal update.

**Comment by connorshea** [comment]
I've got it working now on my fork, although I probably wouldn't recommend it: https://github.com/connorshea/net-http-persistent

I added hoe-gemspec, generated a gemspec, and set the version to 4.1.0.

For others, since I got stuck on this for a little while: if you want to use it with sparql-client or sparql you'll need the `develop` branch of sparql-client, not `master`.

**Comment by kapso** [comment]
Any plans for doing a Ruby 3.0.0 support/release?

Thanks.

**Comment by Keqi** [comment]
Hi!

Bumping this topic. Is there any chance to get Ruby 3 support?

**Comment by deivid-rodriguez** [comment]
This one can be closed now.

**Comment by olleolleolle** [comment]
Thanks, yes, 4.0.1 has this support, closing!
