### ISSUE TITLE
Connection Pool (on master) not reusing connections

### ISSUE THREAD

**Issue by ryansch** [drbrain/net-http-persistent#71]
I've just finished doing some testing of the new connection pool on master in my development environment.  It appears that the pool isn't reusing connections as I'm seeing one additional established connection per request to my elasticsearch server (seen with `lsof`).
- Using `2.9.4` with `bundle exec rails s`:
  1 connection to elasticsearch
- Using `master` with `bundle exec rails s`
  19 connections to elasticsearch (we make 18 requests to ES during app boot)
  Each additional request to elasticsearch increases the established connection count by one

**Comment by ryansch** [comment]
Note: `rails server` is using `thin` (single process, no threads)

**Comment by drbrain** [comment]
Thanks, I'll look into it.

Perhaps the default pools size is ridiculously high: https://github.com/drbrain/net-http-persistent/blob/master/lib/net/http/persistent.rb#L533

**Comment by ryansch** [comment]
Yeah that worked out to a pool size of 1024 for me.

**Comment by drbrain** [comment]
I made to programs to test this, a server:

```ruby
require 'webrick'
require 'pp'

log = WEBrick::Log.new IO::NULL

h = WEBrick::HTTPServer.new Port: 8000, Logger: log, AccessLog: log

c_ids = Hash.new 0

trap 'INT' do
  h.shutdown

  puts
  pp c_ids
end

h.mount_proc '/' do |req, res|
  c_id = req.query['c']
  c_ids[c_id] += 1
  
  p c: c_id
end

h.start
```

and a client:

```ruby
require 'net/http/persistent'

http = Net::HTTP::Persistent.new

uri = URI 'http://localhost:8000'

threads = []

100.times do
  t = Thread.new do
    sleep rand 0.001 # work
    
    http.connection_for uri do |c|
      req_uri = uri + "?c=#{c.object_id}"
      
      req = http.request_setup req_uri
      
      c.http.request req
    end
  end
  
  threads << t
end

threads.each do |t| t.join end
```

The client sends the `object_id` of its `Net::HTTP` object to the server which counts up the different `object_id`s and displays them when you ⌃C the server.

Running on OS X (`ulimit -n` == 2560, or 640 connections) I get:

```
^C
{"70176297025980"=>32,
 "70176297288740"=>15,
 "70176301434020"=>36,
 "70176301726900"=>17}
```

So the connections are being reused across threads.

However, if I increase the number of clients, there's less reuse.  This is probably because WEBrick starts blocking connections due to it defaulting to a maximum of 100 concurrent connections.

Using an example like this can you show non-reuse of connections? I can't reproduce it offhand.

**Comment by ryansch** [comment]
So after doing a deep dive on `Net::HTTP` I decided I didn't want to be coupled to something that used `Timeout.timeout`.  I ended up building https://github.com/aceofsales/faraday_persistent_excon to solve this problem.
