### ISSUE TITLE
td-agent faild to send log to loggly because of net-http-persistent 3.0.0 is not compatible with fluent-plugin-forest

### ISSUE THREAD

**Issue by jogendrajangid1** [drbrain/net-http-persistent#81]
We have found net-http-persistent 3.0.0 not compatible with fluent-plugin-forest. because of that td-agent not able to sent log to loggly using fluent-plugin-forest.

 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505:in `initialize'

**Comment by drbrain** [comment]
net-http-persistent uses [semantic versioning](http://guides.rubygems.org/patterns/#semantic-versioning).  Since the major version changed you must expect to update your software due to API changes in net-http-persistent.

I don't see that [fluent-plugin-forest](https://rubygems.org/gems/fluent-plugin-forest) has an explicit dependency on net-http-persistent so I'm guessing by the path in the error above that you embed it.  

Until you update your dependencies to work with the 3.x series you should downgrade to the newest 2.9.x version.

What is the nature of the incompatibility you encounter?  Maybe I can make a change to mitigate it.
